### ISSUE TITLE
Change language for prompt templates

### ISSUE THREAD

**Issue by tristan-k** [suncloudsmoon/TextCraft#1]
I noticed that the actual prompt templates for the features [Comment](https://github.com/suncloudsmoon/TextCraft/blob/68d98069894677660a1610bbe0f721881e14b75d/Forge.cs#L22), [Review](https://github.com/suncloudsmoon/TextCraft/blob/master/Forge.cs#L208), [Proofread](https://github.com/suncloudsmoon/TextCraft/blob/68d98069894677660a1610bbe0f721881e14b75d/Forge.cs#L242-L243) and [Rewrite](https://github.com/suncloudsmoon/TextCraft/blob/68d98069894677660a1610bbe0f721881e14b75d/Forge.cs#L250-L251) are hard coded in English. Is there anyway to change the language without changing the code and recompile?

**Comment by suncloudsmoon** [comment]
Thanks for bringing this up, @tristan-k. Right now, the language for prompt templates—like Comment, Review, Proofread, and Rewrite—is hardcoded in English in the binary, so changing it requires recompiling. I had thought about making the templates adaptable to other languages, but a few tricky issues came up. For example, a user might have the UI set to one language but still be writing in English (or vice versa), which could lead to prompts in the UI language that don’t match the document’s language, resulting in suboptimal output. Microsoft Word has a way to detect document language, but it’s often inaccurate. While other UI elements are localized through `.resx` files, I left out these prompts thinking that an advanced LLM might pick up on the input language automatically. Let me know if you have any ideas or thoughts on how to approach this!

**Comment by tristan-k** [comment]
I hadn't thought about that. For the time-being and based on `TextCraft` current approach on api endpoints, I would suggest tackling the issue with another environment variable like `TEXTCRAFT_PROMPT_TEMPLATE_LANGUAGE`. Or maybe even let the user decide the prompt template with environment variables for `TEXTCRAFT_PROMPT_TEMPLATE_COMMENT`, `TEXTCRAFT_PROMPT_TEMPLATE_REVIEW`, `TEXTCRAFT_PROMPT_TEMPLATE_PROOFREAD`, and `TEXTCRAFT_PROMPT_TEMPLATE_REWRITE`. Given the target audience of TextCraft is a more techsavy user this seems fitting. It's not elegant but it gets the job done until the issue is solved in more broadly manner.

**Comment by suncloudsmoon** [comment]
I’m happy to share that with version 1.0.6 of TextCraft, this issue is now resolved. You can now either specify the system prompt directly with a user environment variable or, if you prefer, let TextCraft use the translated system prompts automatically, which now support all of Office's display languages.

**Comment by suncloudsmoon** [comment]
I’m happy to share that with version 1.0.6 of TextCraft, this issue is now resolved. You can now either specify the system prompt directly with a user environment variable or, if you prefer, let TextCraft use the translated system prompts automatically, which now support all of Office's display languages.
